services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
        container_name: elasticsearch
        environment:
        - discovery.type=single-node
        volumes:
        - data01:/usr/share/elasticsearch/data
        ports:
        - 9200:9200
        - 9300:9300
            # Configuracion elasticsearch
    logstash:
        image: docker.elastic.co/logstash/logstash:8.5.2
        # Configuracion logstash
    kibana:
        image: docker.elastic.co/kibana/kibana:8.5.2
        container_name: kibana
        ports:
            - 80:5601
        depends_on:
            - elasticsearch
volumes:
    # Configuración de volumenes
    data01:
